var namespaceloos =
[
    [ "DensityTools", "namespaceloos_1_1_density_tools.html", "namespaceloos_1_1_density_tools" ],
    [ "HBonds", null, [
      [ "ErrorWithAtom", "structloos_1_1_h_bonds_1_1_error_with_atom.html", "structloos_1_1_h_bonds_1_1_error_with_atom" ],
      [ "SimpleAtom", "classloos_1_1_h_bonds_1_1_simple_atom.html", "classloos_1_1_h_bonds_1_1_simple_atom" ]
    ] ],
    [ "internal", "namespaceloos_1_1internal.html", "namespaceloos_1_1internal" ],
    [ "Math", "namespaceloos_1_1_math.html", "namespaceloos_1_1_math" ],
    [ "OptionsFramework", "namespaceloos_1_1_options_framework.html", "namespaceloos_1_1_options_framework" ],
    [ "pyloos", null, [
      [ "ConvexHull", null, [
        [ "ConvexHull", "classloos_1_1pyloos_1_1_convex_hull_1_1_convex_hull.html", "classloos_1_1pyloos_1_1_convex_hull_1_1_convex_hull" ],
        [ "ZSliceSelector", "classloos_1_1pyloos_1_1_convex_hull_1_1_z_slice_selector.html", "classloos_1_1pyloos_1_1_convex_hull_1_1_z_slice_selector" ]
      ] ],
      [ "NAMDBin", "namespaceloos_1_1pyloos_1_1_n_a_m_d_bin.html", "namespaceloos_1_1pyloos_1_1_n_a_m_d_bin" ],
      [ "trajectories", "namespaceloos_1_1pyloos_1_1trajectories.html", "namespaceloos_1_1pyloos_1_1trajectories" ]
    ] ],
    [ "AbstractObserver", "classloos_1_1_abstract_observer.html", "classloos_1_1_abstract_observer" ],
    [ "Amber", "classloos_1_1_amber.html", "classloos_1_1_amber" ],
    [ "AmberNetcdf", "classloos_1_1_amber_netcdf.html", "classloos_1_1_amber_netcdf" ],
    [ "AmberRst", "classloos_1_1_amber_rst.html", "classloos_1_1_amber_rst" ],
    [ "AmberTraj", "classloos_1_1_amber_traj.html", "classloos_1_1_amber_traj" ],
    [ "AndSelector", "structloos_1_1_and_selector.html", "structloos_1_1_and_selector" ],
    [ "AscendingSort", "classloos_1_1_ascending_sort.html", "classloos_1_1_ascending_sort" ],
    [ "Atom", "classloos_1_1_atom.html", "classloos_1_1_atom" ],
    [ "AtomCoordsEquals", "structloos_1_1_atom_coords_equals.html", "structloos_1_1_atom_coords_equals" ],
    [ "AtomEquals", "structloos_1_1_atom_equals.html", "structloos_1_1_atom_equals" ],
    [ "AtomicGroup", "classloos_1_1_atomic_group.html", "classloos_1_1_atomic_group" ],
    [ "AtomNameSelector", "structloos_1_1_atom_name_selector.html", "structloos_1_1_atom_name_selector" ],
    [ "AtomSelector", "structloos_1_1_atom_selector.html", "structloos_1_1_atom_selector" ],
    [ "BackboneSelector", "classloos_1_1_backbone_selector.html", "classloos_1_1_backbone_selector" ],
    [ "BasicProgress", "classloos_1_1_basic_progress.html", "classloos_1_1_basic_progress" ],
    [ "BoundFmt", "structloos_1_1_bound_fmt.html", "structloos_1_1_bound_fmt" ],
    [ "CAlphaSelector", "structloos_1_1_c_alpha_selector.html", "structloos_1_1_c_alpha_selector" ],
    [ "CCPDB", "classloos_1_1_c_c_p_d_b.html", "classloos_1_1_c_c_p_d_b" ],
    [ "CHARMM", "classloos_1_1_c_h_a_r_m_m.html", "classloos_1_1_c_h_a_r_m_m" ],
    [ "Coord", "classloos_1_1_coord.html", "classloos_1_1_coord" ],
    [ "DCD", "classloos_1_1_d_c_d.html", "classloos_1_1_d_c_d" ],
    [ "DCDWriter", "classloos_1_1_d_c_d_writer.html", "classloos_1_1_d_c_d_writer" ],
    [ "DescendingSort", "classloos_1_1_descending_sort.html", "classloos_1_1_descending_sort" ],
    [ "EstimatingCounter", "classloos_1_1_estimating_counter.html", "classloos_1_1_estimating_counter" ],
    [ "FileError", "classloos_1_1_file_error.html", "classloos_1_1_file_error" ],
    [ "FileOpenError", "classloos_1_1_file_open_error.html", "classloos_1_1_file_open_error" ],
    [ "FileReadError", "classloos_1_1_file_read_error.html", "classloos_1_1_file_read_error" ],
    [ "FileReadErrorWithLine", "classloos_1_1_file_read_error_with_line.html", "classloos_1_1_file_read_error_with_line" ],
    [ "FileWriteError", "classloos_1_1_file_write_error.html", "classloos_1_1_file_write_error" ],
    [ "Fmt", "classloos_1_1_fmt.html", "classloos_1_1_fmt" ],
    [ "Gromacs", "classloos_1_1_gromacs.html", "classloos_1_1_gromacs" ],
    [ "HBondDetector", "classloos_1_1_h_bond_detector.html", "classloos_1_1_h_bond_detector" ],
    [ "HeavyAtomSelector", "structloos_1_1_heavy_atom_selector.html", "structloos_1_1_heavy_atom_selector" ],
    [ "HeavySolventSelector", "structloos_1_1_heavy_solvent_selector.html", "structloos_1_1_heavy_solvent_selector" ],
    [ "HydrogenSelector", "structloos_1_1_hydrogen_selector.html", "structloos_1_1_hydrogen_selector" ],
    [ "IndexSelector", "structloos_1_1_index_selector.html", "structloos_1_1_index_selector" ],
    [ "Kernel", "classloos_1_1_kernel.html", "classloos_1_1_kernel" ],
    [ "KernelSelector", "classloos_1_1_kernel_selector.html", "classloos_1_1_kernel_selector" ],
    [ "LineReader", "classloos_1_1_line_reader.html", "classloos_1_1_line_reader" ],
    [ "LOOSError", "classloos_1_1_l_o_o_s_error.html", "classloos_1_1_l_o_o_s_error" ],
    [ "Matrix44", "classloos_1_1_matrix44.html", "classloos_1_1_matrix44" ],
    [ "MatrixReadError", "classloos_1_1_matrix_read_error.html", "classloos_1_1_matrix_read_error" ],
    [ "MatrixReadImpl", "structloos_1_1_matrix_read_impl.html", null ],
    [ "MatrixReadImpl< T, Math::Triangular, S >", "structloos_1_1_matrix_read_impl_3_01_t_00_01_math_1_1_triangular_00_01_s_01_4.html", null ],
    [ "MatrixReadImpl< T, P, Math::SparseArray >", "structloos_1_1_matrix_read_impl_3_01_t_00_01_p_00_01_math_1_1_sparse_array_01_4.html", null ],
    [ "MatrixWriteImpl", "structloos_1_1_matrix_write_impl.html", null ],
    [ "MatrixWriteImpl< T, Math::Triangular, S, F >", "structloos_1_1_matrix_write_impl_3_01_t_00_01_math_1_1_triangular_00_01_s_00_01_f_01_4.html", null ],
    [ "MatrixWriteImpl< T, P, Math::SparseArray, F >", "structloos_1_1_matrix_write_impl_3_01_t_00_01_p_00_01_math_1_1_sparse_array_00_01_f_01_4.html", null ],
    [ "MultiTrajectory", "classloos_1_1_multi_trajectory.html", "classloos_1_1_multi_trajectory" ],
    [ "NotSelector", "structloos_1_1_not_selector.html", "structloos_1_1_not_selector" ],
    [ "NumericalError", "classloos_1_1_numerical_error.html", "classloos_1_1_numerical_error" ],
    [ "OptionsError", "classloos_1_1_options_error.html", "classloos_1_1_options_error" ],
    [ "OrSelector", "structloos_1_1_or_selector.html", "structloos_1_1_or_selector" ],
    [ "ParseError", "classloos_1_1_parse_error.html", "classloos_1_1_parse_error" ],
    [ "Parser", "classloos_1_1_parser.html", "classloos_1_1_parser" ],
    [ "ParserDriver", "structloos_1_1_parser_driver.html", "structloos_1_1_parser_driver" ],
    [ "PDB", "classloos_1_1_p_d_b.html", "classloos_1_1_p_d_b" ],
    [ "PDBTraj", "classloos_1_1_p_d_b_traj.html", "classloos_1_1_p_d_b_traj" ],
    [ "PercentProgress", "classloos_1_1_percent_progress.html", "classloos_1_1_percent_progress" ],
    [ "PercentProgressWithTime", "classloos_1_1_percent_progress_with_time.html", "classloos_1_1_percent_progress_with_time" ],
    [ "PercentTrigger", "classloos_1_1_percent_trigger.html", "classloos_1_1_percent_trigger" ],
    [ "PeriodicBox", "classloos_1_1_periodic_box.html", "classloos_1_1_periodic_box" ],
    [ "PreciseMatrixFormatter", "classloos_1_1_precise_matrix_formatter.html", "classloos_1_1_precise_matrix_formatter" ],
    [ "ProgressCounter", "classloos_1_1_progress_counter.html", "classloos_1_1_progress_counter" ],
    [ "PSF", "classloos_1_1_p_s_f.html", "classloos_1_1_p_s_f" ],
    [ "Remarks", "classloos_1_1_remarks.html", "classloos_1_1_remarks" ],
    [ "ResidRangeSelector", "structloos_1_1_resid_range_selector.html", "structloos_1_1_resid_range_selector" ],
    [ "RnaSuite", "classloos_1_1_rna_suite.html", "classloos_1_1_rna_suite" ],
    [ "ScientificMatrixFormatter", "classloos_1_1_scientific_matrix_formatter.html", "classloos_1_1_scientific_matrix_formatter" ],
    [ "SegidSelector", "structloos_1_1_segid_selector.html", "structloos_1_1_segid_selector" ],
    [ "SharedPeriodicBox", "classloos_1_1_shared_periodic_box.html", "classloos_1_1_shared_periodic_box" ],
    [ "SimpleCounter", "classloos_1_1_simple_counter.html", "classloos_1_1_simple_counter" ],
    [ "SolventSelector", "structloos_1_1_solvent_selector.html", "structloos_1_1_solvent_selector" ],
    [ "StreamWrapper", "classloos_1_1_stream_wrapper.html", "classloos_1_1_stream_wrapper" ],
    [ "Timer", "classloos_1_1_timer.html", "classloos_1_1_timer" ],
    [ "TimeSeries", "classloos_1_1_time_series.html", "classloos_1_1_time_series" ],
    [ "TinkerArc", "classloos_1_1_tinker_arc.html", "classloos_1_1_tinker_arc" ],
    [ "TinkerXYZ", "classloos_1_1_tinker_x_y_z.html", "classloos_1_1_tinker_x_y_z" ],
    [ "Trajectory", "classloos_1_1_trajectory.html", "classloos_1_1_trajectory" ],
    [ "TrajectoryWriter", "classloos_1_1_trajectory_writer.html", "classloos_1_1_trajectory_writer" ],
    [ "TriggerAlways", "classloos_1_1_trigger_always.html", "classloos_1_1_trigger_always" ],
    [ "TriggerEvery", "classloos_1_1_trigger_every.html", "classloos_1_1_trigger_every" ],
    [ "TRR", "classloos_1_1_t_r_r.html", "classloos_1_1_t_r_r" ],
    [ "UniqueStrings", "classloos_1_1_unique_strings.html", "classloos_1_1_unique_strings" ],
    [ "UnitCell", "classloos_1_1_unit_cell.html", "classloos_1_1_unit_cell" ],
    [ "UnsetProperty", "classloos_1_1_unset_property.html", "classloos_1_1_unset_property" ],
    [ "UserTimer", "classloos_1_1_user_timer.html", "classloos_1_1_user_timer" ],
    [ "WallTimer", "classloos_1_1_wall_timer.html", "classloos_1_1_wall_timer" ],
    [ "Weights", "classloos_1_1_weights.html", "classloos_1_1_weights" ],
    [ "XDRDataSizeError", "structloos_1_1_x_d_r_data_size_error.html", "structloos_1_1_x_d_r_data_size_error" ],
    [ "XForm", "classloos_1_1_x_form.html", "classloos_1_1_x_form" ],
    [ "XTC", "classloos_1_1_x_t_c.html", "classloos_1_1_x_t_c" ],
    [ "XTCWriter", "classloos_1_1_x_t_c_writer.html", "classloos_1_1_x_t_c_writer" ],
    [ "ZSliceSelector", "structloos_1_1_z_slice_selector.html", "structloos_1_1_z_slice_selector" ]
];