# SConscript
# (c) 2008 Tod D. Romo
#
# Grossfield Lab
# Department fo Biochemistry & Biophysics
# University of Rochester Medical School
#
#


Import('env')



test_apps = 'atomic_grp_tst pdb_tst parser_tst princ_axes_tst timeseries_tst'


atomic_grp_tst = env.Program('atomic-group-test.cpp')
pdb_tst = env.Program('pdb-test.cpp')
parser_tst = env.Program('parser-test.cpp')
princ_axes_tst = env.Program('princ_axes_tst.cpp')
timeseries_tst = env.Program('timeseries-test.cpp')

Return(test_apps)
