#!/usr/bin/env python
#  This file is part of LOOS.
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2009 Tod D. Romo
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.



import sys

Import('env')

clone = env.Clone()
clone.Append(LIBS = ['loos'])

apps = 'gnm enmovie flucc2b psf-masses heavy-ca'
install_apps = apps + ' vsa anm'

list = []

for name in Split(apps):
    fname = name + '.cpp'
    prog = clone.Program(fname)
    list.append(prog)

PREFIX = env['PREFIX']


# Special apps...

vsa = clone.Program("vsa", ["vsa.cpp", "hessian.cpp"])
list.append(vsa)

vsa = clone.Program("anm", ["anm.cpp", "hessian.cpp"])
list.append(vsa)


loos_tools = env.Install(PREFIX + '/bin', Split(install_apps))
env.Alias('nm_tools_install', loos_tools)

Return('list')
