#!/usr/bin/env python3
#  This file is part of LOOS.
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2021, Alan Grossfield, Grossfield Lab
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os

Import('env')

pyloos_directory = []

files = 'ConvexHull.py NAMDBin.py __init__.py alignment.py ensembles.py '
files += 'subspace.py trajectories.py '

if env.USING_CONDA:
    python_lib_path = list(filter(lambda x: x.endswith("site-packages"),
                           sys.path))[0] + '/loos/pyloos/'
else:
    PREFIX = env['PREFIX'] + '/pyloos/'

if int(env['pyloos']):
    if env.USING_CONDA:
        p = python_lib_path
    else:
        p = PREFIX
    for d in Split(files):
        env.Install(p + d, d)

Return('pyloos_directory')
