# SConscript
# (c) 2008 Tod D. Romo
#
# Grossfield Lab
# Department of Biochemistry & Biophysics
# University of Rochester Medical School
#
#

import sys

Import('env')

example_apps = 'coord-example dcd-example pdb-example dcd-example2 dcd-example3 psf-example pdb-parsed pdb-splitter'

list = []

for name in Split(example_apps):
    fname = name + '.cpp'
    prog = env.Program(fname)
    list.append(prog)

Return('list')
