#!/usr/bin/env python
# SConscript for Convergence Tools
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2010 Tod D. Romo
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys

Import('env')

clone = env.Clone()
clone.Prepend(LIBS = ['loos'])

PREFIX = env['PREFIX']

# Scripts

scripts = 'bootstrap_overlap.pl decorr_plot.sh effsize.pl'

# Stand-alone apps...

bcomlib = clone.Object('bcomlib.cpp')

bcom = clone.Program('bcom', ['bcom.cpp', bcomlib])
boot_bcom = clone.Program('boot_bcom', ['boot_bcom.cpp', bcomlib])

fidlib = clone.Object('fid-lib.cpp')

fidpick = clone.Program('fidpick.cpp')
ufidpick = clone.Program('ufidpick', ['ufidpick.cpp', fidlib])
sortfids = clone.Program('sortfids.cpp')

decorr_time = clone.Program('decorr_time', ['decorr_time.cpp', fidlib])

hierarchy = clone.Program('hierarchy.cpp')
neff = clone.Program('neff.cpp')

block_average = clone.Program('block_average.cpp')

avgconv = clone.Program('avgconv.cpp')

list = [ bcom, boot_bcom, fidpick, sortfids, ufidpick, decorr_time, hierarchy, neff, block_average, avgconv ]

install_apps = list + Split(scripts)


conv_tools = env.Install(PREFIX + '/bin', Split(install_apps))
env.Alias('conv_tools_install', conv_tools)


Return('list')
