#!/usr/bin/env python3
#  This file is part of LOOS.
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2008, Tod D. Romo
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

Import('env')
Import('loos')

clone = env.Clone()
clone.Prepend(LIBS = [loos])

files = 'suitename_definitions.dat stack_vals.json'
PREFIX = env['PREFIX']

if env.USING_CONDA:
    share_path = os.path.join(PREFIX, "share", "loos")
else:
    share_path = os.path.join(PREFIX, "share")

shared_files = env.Install(share_path, Split(files))

shared_list = Split(files)

Return('shared_list')
