#!/usr/bin/env python3

import subprocess
import shutil

flag_line = '#### EXES AUTOGENERATED'

# identify binaries
# stolen from git-ignore-exes.sh
command_string ="find . \( -name .git -o -name .sconf_temp -o -name '*.so' \) -prune \
     -o -type f -a -perm /111 -exec file {} \; |\
    grep ELF"

completed = subprocess.run(command_string,
                           capture_output=True,
                           shell=True,
                           universal_newlines=True,
                           text=True)
binaries = []
lines = completed.stdout.split('\n')
for line in lines:
    if len(line) > 0:
        name, other = line.split(': ')
        binaries.append(name[2:])


# back up gitignore
shutil.move('.gitignore', '.gitignore-prev')

input = open('.gitignore-prev')
output = open('.gitignore', "w")
for line in input:
    output.write(line)
    if line.startswith(flag_line):
        break
input.close()

for line in sorted(binaries):
    print(line)
    output.write(line + "\n")
output.close()
