var dir_25b71a3164425d524512c79461fe0b2c =
[
    [ "all_contacts.py", "all__contacts_8py_source.html", null ],
    [ "axis_with_membrane.py", "axis__with__membrane_8py_source.html", null ],
    [ "center_molecule.py", "center__molecule_8py_source.html", null ],
    [ "cluster-structures.py", "cluster-structures_8py_source.html", null ],
    [ "cylindrical-density.py", "cylindrical-density_8py_source.html", null ],
    [ "cylindrical-thickness.py", "cylindrical-thickness_8py_source.html", null ],
    [ "domain.py", "domain_8py_source.html", null ],
    [ "flip_chirality.py", "flip__chirality_8py_source.html", null ],
    [ "helix_axes.py", "helix__axes_8py_source.html", null ],
    [ "hierarchical-cluster.py", "hierarchical-cluster_8py_source.html", null ],
    [ "inside_helices.py", "inside__helices_8py_source.html", null ],
    [ "native-hbs.py", "native-hbs_8py_source.html", null ],
    [ "packing_score_per_res.py", "packing__score__per__res_8py_source.html", null ],
    [ "protein_tilt.py", "protein__tilt_8py_source.html", null ],
    [ "renum-by-mol.py", "renum-by-mol_8py_source.html", null ],
    [ "rmsd_to_average.py", "rmsd__to__average_8py_source.html", null ],
    [ "set_segids.py", "set__segids_8py_source.html", null ],
    [ "simple_model_calc.py", "simple__model__calc_8py_source.html", null ],
    [ "simple_model_transform.py", "simple__model__transform_8py_source.html", null ],
    [ "simple_traj_calc.py", "simple__traj__calc_8py_source.html", null ],
    [ "simple_traj_transform.py", "simple__traj__transform_8py_source.html", null ],
    [ "total_charge.py", "total__charge_8py_source.html", null ]
];