#!/usr/bin/env python
#  This file is part of LOOS.
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2010 Tod D. Romo
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.



import sys

Import('env')

clone = env.Clone()
clone.Prepend(LIBS = ['loos'])

PREFIX = env['PREFIX']

list = []

hbonds_core = clone.Object('hbonds_core.cpp')

hbonds_corr = clone.Program('hbonds_correlation', ['hbonds_correlation.cpp', hbonds_core])
list.append(hbonds_corr)

better_hbonds = clone.Program('hbonds', ['hbonds.cpp', hbonds_core])
list.append(better_hbonds)

hbonds_as_matrix = clone.Program('hbonds_as_matrix', ['hbonds_as_matrix.cpp', hbonds_core])
list.append(hbonds_as_matrix)

install_apps = 'hbonds hbonds_correlation hbonds_as_matrix'

loos_tools = env.Install(PREFIX + '/bin', Split(install_apps))
env.Alias('h_tools_install', loos_tools)

Return('list')
