#!/usr/bin/perl -w
#
# octavex - extracts embedded OCTAVE data from a LOOS output/log
#

#  This file is part of LOOS.
#
#  LOOS (Lightweight Object-Oriented Structure library)
#  Copyright (c) 2008, Tod D. Romo
#  Department of Biochemistry and Biophysics
#  School of Medicine & Dentistry, University of Rochester
#
#  This package (LOOS) is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation under version 3 of the License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


$state = 0;
while (<>) {
  if ($state == 0) {
    if (/^<OCTAVE>/) {
      $state = 1;
    }
  } elsif ($state == 1) {
    if (m@^</OCTAVE>@) {
      $state = 0;
    } else {
      print;
    }
  }
}


