# SConscript
# (c) 2008 Tod D. Romo
#
# Grossfield Lab
# Department of Biochemistry & Biophysics
# University of Rochester Medical School
#
#

import sys

Import('env')

apps = 'density-dist center-pdb pdb2matlab dcdframe2pdb contacts order_params bounding aligner'

list = []

for name in Split(apps):
    fname = name + '.cpp'
    prog = env.Program(fname)
    list.append(prog)

Return('list')
